import { DIVISIONS } from '../../constants.js';
import { sharedCSS, fabCSS } from '../css.js';
import { navFab, navFabJS, defaultJerseys, footer } from '../components.js';

export function brandPage(config, teamId, brand, saved, session, myTeams) {
  brand = brand || {};
  var jerseys = brand.jerseys || defaultJerseys();
  function logoField(label, inputName, hasImg, imgPath) {
    var id = "lf-" + inputName;
    var editor = "<div class=\"logo-editor\" id=\"" + id + "-ed\" style=\"display:none\">"
      + "<div class=\"logo-ed-previews\">"
      + "<div class=\"logo-ed-col\"><div class=\"logo-ed-lbl\">Original</div><img class=\"logo-ed-img\" id=\"" + id + "-ed-orig\" /></div>"
      + "<div class=\"logo-ed-col\" id=\"" + id + "-ed-result-col\" style=\"display:none\"><div class=\"logo-ed-lbl\">Background Removed</div><img class=\"logo-ed-img checker\" id=\"" + id + "-ed-result\" /></div>"
      + "</div>"
      + "<div class=\"logo-ed-actions\">"
      + "<button type=\"button\" class=\"logo-rmbg-btn\" id=\"" + id + "-ed-rmbg\" onclick=\"lfRemoveBg('" + id + "')\">Remove Background</button>"
      + "<button type=\"button\" class=\"logo-use-btn\" id=\"" + id + "-ed-use\" style=\"display:none\" onclick=\"lfUseResult('" + id + "')\">&#10003; Use This</button>"
      + "</div></div>";
    if (hasImg) {
      return "<div class=\"field\"><label>" + label + "</label>"
        + "<div id=\"" + id + "-preview\">"
        + "<div class=\"logo-thumb-wrap\">"
        + "<img src=\"" + imgPath + "\" alt=\"current logo\" class=\"logo-thumb\" id=\"" + id + "-current-img\">"
        + "<button type=\"button\" class=\"logo-x\" onclick=\"lfSwitch('" + id + "')\" title=\"Change logo\">&times;</button>"
        + "</div>"
        + "<div style=\"margin-top:6px;display:flex;gap:8px;align-items:center\">"
        + "<button type=\"button\" class=\"logo-rmbg-btn\" id=\"" + id + "-existing-rmbg\" onclick=\"lfRemoveBgExisting('" + id + "','" + imgPath + "')\">Remove Background</button>"
        + "<span id=\"" + id + "-existing-use\" style=\"display:none\"><button type=\"button\" class=\"logo-use-btn\" onclick=\"lfUseExistingResult('" + id + "','" + inputName + "')\">&#10003; Use This</button></span>"
        + "</div>"
        + "<div class=\"logo-ed-previews\" id=\"" + id + "-existing-result-col\" style=\"display:none;margin-top:10px\">"
        + "<div class=\"logo-ed-col\"><div class=\"logo-ed-lbl\">Result</div><img class=\"logo-ed-img checker\" id=\"" + id + "-existing-result\" /></div>"
        + "</div>"
        + "<input type=\"file\" name=\"" + inputName + "\" id=\"" + id + "-input\" accept=\"image/*\" style=\"display:none\" onchange=\"lfPreview('" + id + "',this)\">"
        + "</div>"
        + "<div id=\"" + id + "-upload\" style=\"display:none\">"
        + "<input type=\"file\" id=\"" + id + "-picker\" accept=\"image/*\" onchange=\"lfPreview('" + id + "',this)\">"
        + "<small>Leave blank to keep current. <a href=\"#\" style=\"color:#888\" onclick=\"lfCancel('" + id + "');return false\">Cancel</a></small>"
        + editor
        + "</div>"
        + "</div>";
    }
    return "<div class=\"field\"><label>" + label + "</label>"
      + "<input type=\"file\" name=\"" + inputName + "\" id=\"" + id + "-input\" accept=\"image/*\" onchange=\"lfPreview('" + id + "',this)\">"
      + "<small>Upload a PNG or JPG (square works best).</small>"
      + editor
      + "</div>";
  }
  function jerseyRow(j) {
    return "<div class=\"jersey-row\">"
      + "<label class=\"jersey-label\">" + j.id.charAt(0).toUpperCase() + j.id.slice(1) + "</label>"
      + "<input type=\"color\" name=\"jersey_" + j.id + "_color\" value=\"" + (j.color || "#1a1a1a") + "\" style=\"flex-shrink:0\">"
      + "<input type=\"text\" name=\"jersey_" + j.id + "_label\" value=\"" + j.label + "\" placeholder=\"e.g. Black (Home)\" style=\"flex:1\">"
      + "</div>";
  }
  return "<!DOCTYPE html><html lang=\"en\"><head>"
    + "<meta charset=\"UTF-8\"><meta name=\"viewport\" content=\"width=device-width,initial-scale=1.0\">"
    + "<title>" + config.name + " \u2014 Team Settings</title>"
    + "<style>" + sharedCSS(config)
    + "body{background:#f5f2ec;padding:0;min-height:100vh}"
    + ".brand-wrap{display:flex;justify-content:center;padding:24px 16px}"
    + ".brand-card{background:white;border-radius:6px;padding:32px;max-width:860px;width:100%;box-shadow:0 2px 12px rgba(0,0,0,.08)}"
    + ".brand-topbar{display:flex;justify-content:space-between;align-items:center;padding:12px 24px;max-width:860px;margin:0 auto}"
    + ".back{font-size:12px;color:" + (config.primaryColor||"#c0392b") + ";text-decoration:none;text-transform:uppercase;letter-spacing:1px}"
    + "h2{font-size:18px;text-transform:uppercase;letter-spacing:2px;margin-bottom:24px}"
    + "h3{font-size:12px;text-transform:uppercase;letter-spacing:2px;color:#aaa;margin:24px 0 16px;border-top:1px solid #eee;padding-top:20px}"
    + ".field{margin-bottom:18px}"
    + "label{display:block;font-size:11px;text-transform:uppercase;letter-spacing:1px;color:#888;margin-bottom:5px}"
    + "input[type=text]{width:100%;border:1px solid #ddd;border-radius:3px;padding:8px 10px;font-family:inherit;font-size:14px}"
    + "input[type=file]{font-family:inherit;font-size:13px;color:#555}"
    + "small{display:block;font-size:11px;color:#aaa;margin-top:4px}"
    + ".color-row{display:flex;align-items:center;gap:10px}"
    + "input[type=color]{width:44px;height:36px;border:1px solid #ddd;border-radius:3px;padding:2px;cursor:pointer;flex-shrink:0}"
    + ".color-row input[type=text]{flex:1}"
    + ".logo-thumb-wrap{display:inline-block;position:relative;margin-bottom:8px}"
    + ".logo-thumb{display:block;height:80px;width:80px;object-fit:contain;background:#f5f2ec;border-radius:4px;border:1px solid #e0ddd8}"
    + ".logo-x{position:absolute;top:-8px;right:-8px;width:22px;height:22px;border-radius:50%;background:#1a1a1a;color:white;border:none;font-size:14px;line-height:1;cursor:pointer;display:flex;align-items:center;justify-content:center;padding:0}"
    + ".logo-x:hover{background:#c0392b}"
    + ".logo-editor{margin-top:12px;background:#f0ede8;border-radius:6px;padding:14px}"
    + ".logo-ed-previews{display:flex;gap:20px;margin-bottom:12px}"
    + ".logo-ed-col{display:flex;flex-direction:column;align-items:center;gap:6px}"
    + ".logo-ed-lbl{font-size:10px;text-transform:uppercase;letter-spacing:1px;color:#888}"
    + ".logo-ed-img{width:90px;height:90px;object-fit:contain;background:white;border-radius:4px;border:1px solid #e0ddd8}"
    + ".checker{background-image:linear-gradient(45deg,#ddd 25%,transparent 25%),linear-gradient(-45deg,#ddd 25%,transparent 25%),linear-gradient(45deg,transparent 75%,#ddd 75%),linear-gradient(-45deg,transparent 75%,#ddd 75%);background-size:8px 8px;background-position:0 0,0 4px,4px -4px,-4px 0;background-color:white}"
    + ".logo-ed-actions{display:flex;gap:8px;align-items:center}"
    + ".logo-rmbg-btn{padding:7px 14px;background:#1a1a1a;color:white;border:none;border-radius:4px;font-family:inherit;font-size:12px;text-transform:uppercase;letter-spacing:1px;cursor:pointer}"
    + ".logo-rmbg-btn:hover:not(:disabled){background:#333}"
    + ".logo-rmbg-btn:disabled{background:#bbb;cursor:default}"
    + ".logo-use-btn{padding:7px 14px;background:#27ae60;color:white;border:none;border-radius:4px;font-family:inherit;font-size:12px;text-transform:uppercase;letter-spacing:1px;cursor:pointer}"
    + ".logo-use-btn:hover{background:#219a52}"
    + ".jersey-row{display:flex;align-items:center;gap:10px;margin-bottom:12px}"
    + ".jersey-label{font-size:11px;text-transform:uppercase;letter-spacing:1px;color:#888;margin-bottom:0;min-width:40px;flex-shrink:0}"
    + ".add-alt-btn{display:block;width:100%;margin-bottom:12px;padding:8px;background:none;border:2px dashed #ddd;border-radius:4px;font-family:inherit;font-size:11px;text-transform:uppercase;letter-spacing:1px;color:#aaa;cursor:pointer}"
    + ".add-alt-btn:hover{border-color:#888;color:#888}"
    + ".remove-btn{background:none;border:none;color:#ccc;font-size:20px;cursor:pointer;padding:0 2px;line-height:1;flex-shrink:0}"
    + ".remove-btn:hover{color:#c0392b}"
    + ".btn-row{display:flex;gap:10px;margin-top:24px}"
    + ".btn{font-family:inherit;font-size:13px;text-transform:uppercase;letter-spacing:1px;padding:9px 20px;border-radius:3px;cursor:pointer;border:none}"
    + ".btn-save{background:#1a1a1a;color:white}.btn-save:hover{background:#333}"
    + ".btn-back{background:transparent;color:#1a1a1a;border:2px solid #1a1a1a}.btn-back:hover{background:#1a1a1a;color:white}"
    + (saved ? ".notice{background:#e8f5e9;color:#2e7d32;padding:10px 14px;border-radius:3px;font-size:13px;margin-bottom:20px}" : "")
    + fabCSS(config)
    + "</style></head><body>"
    + "<div class=\"brand-topbar\"><a href=\"/" + teamId + "/\" class=\"back\">\u2190 Lineup</a>" + navFab(config, teamId, session, myTeams, "brand") + "</div>"
    + "<div class=\"brand-wrap\"><div class=\"brand-card\">"
    + "<h2>Team Settings \u2014 " + config.name + "</h2>"
    + (saved ? "<div class=\"notice\">&#10003; Saved!</div>" : "")
    + "<form method=\"POST\" enctype=\"multipart/form-data\" action=\"/" + teamId + "/brand\">"
    + "<h3>Colors</h3>"
    + "<div class=\"field\"><label>Primary Color</label>"
    + "<div class=\"color-row\"><input type=\"color\" id=\"pc-picker\" value=\"" + (config.primaryColor || "#c0392b") + "\" oninput=\"document.getElementById('pc-hex').value=this.value\">"
    + "<input type=\"text\" id=\"pc-hex\" name=\"primaryColor\" value=\"" + (config.primaryColor || "#c0392b") + "\" oninput=\"document.getElementById('pc-picker').value=this.value\" pattern=\"#[0-9a-fA-F]{6}\" placeholder=\"#c0392b\"></div></div>"
    + "<h3>Jersey Colors</h3>"
    + (function() {
        var homeJ = jerseys.find(function(j){return j.id==="home";}) || {id:"home",label:"Black",color:"#1a1a1a"};
        var awayJ = jerseys.find(function(j){return j.id==="away";}) || {id:"away",label:"White",color:"#1a1a1a"};
        var altJ  = jerseys.find(function(j){return j.id==="alt";})  || {id:"alt", label:"",     color:"#c0392b"};
        var hasAlt = !!jerseys.find(function(j){return j.id==="alt" && j.label;});
        return jerseyRow(homeJ) + jerseyRow(awayJ)
          + "<div class=\"jersey-row\" id=\"alt-row\"" + (!hasAlt ? " style=\"display:none\"" : "") + ">"
          + "<label class=\"jersey-label\">Alt</label>"
          + "<input type=\"color\" name=\"jersey_alt_color\" value=\"" + altJ.color + "\" style=\"flex-shrink:0\">"
          + "<input type=\"text\" name=\"jersey_alt_label\" id=\"alt-label-input\" value=\"" + altJ.label + "\" placeholder=\"e.g. Red\" style=\"flex:1\">"
          + "<button type=\"button\" class=\"remove-btn\" onclick=\"removeAlt()\" title=\"Remove\">&times;</button>"
          + "</div>"
          + "<button type=\"button\" id=\"add-alt-btn\" class=\"add-alt-btn\" onclick=\"addAlt()\"" + (hasAlt ? " style=\"display:none\"" : "") + ">+ Add Alternate Jersey</button>";
      })()
    + "<h3>ChillerStats</h3><div class=\"field\"><label>Team URL</label><input type=\"url\" name=\"chillerUrl\" value=\"" + (config.chillerTeamId ? "https://chillerstats.com/team/stats.cfm?TeamID=" + config.chillerTeamId : "") + "\" placeholder=\"https://chillerstats.com/team/stats.cfm?TeamID=...\" style=\"width:100%;border:1px solid #ddd;border-radius:3px;padding:8px 10px;font-family:inherit;font-size:13px\" /><small style=\"margin-top:4px;display:block\">Update if your TeamID changes each session.</small></div>"
    + "<h3>Division</h3><div class=\"field\"><select name=\"division\" style=\"width:100%;border:1px solid #ddd;border-radius:3px;padding:8px 10px;font-family:inherit;font-size:14px;background:white\"><option value=\"\">No division set</option>" + DIVISIONS.map(function(d){return "<option value=\""+d+"\""+(config.division===d?" selected":"")+">"+d+"</option>";}).join("") + "</select></div>"
    + "<h3>Lineup Options</h3>"
    + (function() {
        var curFwd = brand.fwdLines || config.fwdLines || 3;
        var curDef = brand.defLines || (brand.threeDefLines ? 3 : (config.defLines || 2));
        var sel = "width:100%;border:1px solid #ddd;border-radius:3px;padding:8px 10px;font-family:inherit;font-size:14px;background:white";
        return "<div class=\"field\"><label>Forward Lines</label><select name=\"fwdLines\" style=\"" + sel + "\">"
          + "<option value=\"2\"" + (curFwd == 2 ? " selected" : "") + ">2 Lines</option>"
          + "<option value=\"3\"" + (curFwd == 3 ? " selected" : "") + ">3 Lines</option>"
          + "</select></div>"
          + "<div class=\"field\"><label>Defensive Lines</label><select name=\"defLines\" style=\"" + sel + "\">"
          + "<option value=\"2\"" + (curDef == 2 ? " selected" : "") + ">2 Lines</option>"
          + "<option value=\"3\"" + (curDef == 3 ? " selected" : "") + ">3 Lines</option>"
          + "</select></div>";
      })()
    + "<h3>Logo</h3>"
    + logoField("Main Logo", "logoMain", brand.hasLogoMain, "/" + teamId + "/logo/main")
    + "<div class=\"btn-row\">"
    + "<button class=\"btn btn-save\" type=\"submit\">Save</button>"
    + "<a href=\"/" + teamId + "/\"><button class=\"btn btn-back\" type=\"button\">Back to Lineup</button></a>"
    + "</div></form>"
    + footer(config, false, true)
    + "</div></div>"
    + "<script>"
    + "function addAlt(){document.getElementById('alt-row').style.display='flex';document.getElementById('add-alt-btn').style.display='none';}"
    + "function removeAlt(){document.getElementById('alt-row').style.display='none';document.getElementById('add-alt-btn').style.display='';document.getElementById('alt-label-input').value='';}"
    + "var lfBlobs={};"
    + "function lfSwitch(id){document.getElementById(id+'-preview').style.display='none';document.getElementById(id+'-upload').style.display='block';}"
    + "function lfCancel(id){document.getElementById(id+'-preview').style.display='';document.getElementById(id+'-upload').style.display='none';document.getElementById(id+'-ed').style.display='none';}"
    // lfPreview: for hasImg, picker has no name so we copy file into named input via DataTransfer
    + "function lfPreview(id,input){"
    +   "if(!input.files||!input.files[0])return;"
    +   "var named=document.getElementById(id+'-input');"
    +   "if(named&&named!==input){var dt=new DataTransfer();dt.items.add(input.files[0]);named.files=dt.files;}"
    +   "var url=URL.createObjectURL(input.files[0]);"
    +   "document.getElementById(id+'-ed-orig').src=url;"
    +   "document.getElementById(id+'-ed-result-col').style.display='none';"
    +   "document.getElementById(id+'-ed-use').style.display='none';"
    +   "var b=document.getElementById(id+'-ed-rmbg');b.textContent='Remove Background';b.disabled=false;"
    +   "document.getElementById(id+'-ed').style.display='block';"
    +   "lfBlobs[id]=null;"
    + "}"
    + "async function lfRunRemoveBg(sourceBlob){"
    +   "var {AutoModel,AutoProcessor,env,RawImage}=await import('https://cdn.jsdelivr.net/npm/@huggingface/transformers@3.4.1/+esm');"
    +   "env.allowLocalModels=false;"
    +   "var MODEL='briaai/RMBG-1.4';"
    +   "var model=await AutoModel.from_pretrained(MODEL,{config:{model_type:'custom'}});"
    +   "var processor=await AutoProcessor.from_pretrained(MODEL,{config:{do_normalize:true,do_pad:false,do_rescale:true,do_resize:true,image_mean:[0.5,0.5,0.5],image_std:[0.5,0.5,0.5],resample:2,rescale_factor:0.00392156862745098,size:{width:1024,height:1024}}});"
    +   "var url=URL.createObjectURL(sourceBlob);"
    +   "var image=await RawImage.fromURL(url);"
    +   "URL.revokeObjectURL(url);"
    +   "var inputs=await processor(image);"
    +   "var output=await model({input:inputs.pixel_values});"
    +   "var mask=await RawImage.fromTensor(output.output.squeeze(0).mul(255).to('uint8')).resize(image.width,image.height);"
    +   "var canvas=document.createElement('canvas');canvas.width=image.width;canvas.height=image.height;"
    +   "var ctx=canvas.getContext('2d');"
    +   "ctx.drawImage(image.toCanvas(),0,0);"
    +   "var imgData=ctx.getImageData(0,0,image.width,image.height);"
    +   "for(var i=0;i<mask.data.length;i++)imgData.data[i*4+3]=mask.data[i];"
    +   "ctx.putImageData(imgData,0,0);"
    +   "return new Promise(function(res){canvas.toBlob(res,'image/png');});"
    + "}"
    + "async function lfRemoveBg(id){"
    +   "var btn=document.getElementById(id+'-ed-rmbg');"
    +   "btn.disabled=true;btn.textContent='Processing\u2026';"
    +   "try{"
    +     "var file=document.getElementById(id+'-input').files[0];"
    +     "var blob=await lfRunRemoveBg(file);"
    +     "lfBlobs[id]=blob;"
    +     "document.getElementById(id+'-ed-result').src=URL.createObjectURL(blob);"
    +     "document.getElementById(id+'-ed-result-col').style.display='flex';"
    +     "document.getElementById(id+'-ed-use').style.display='';"
    +     "btn.textContent='Remove Background';btn.disabled=false;"
    +   "}catch(e){btn.textContent='Failed \u2013 Try Again';btn.disabled=false;console.error('rmbg:',e);alert(e.message);}"
    + "}"
    + "function lfUseResult(id){"
    +   "var blob=lfBlobs[id];if(!blob)return;"
    +   "var input=document.getElementById(id+'-input');"
    +   "var dt=new DataTransfer();dt.items.add(new File([blob],'logo.png',{type:'image/png'}));input.files=dt.files;"
    +   "document.getElementById(id+'-ed-orig').src=document.getElementById(id+'-ed-result').src;"
    +   "document.getElementById(id+'-ed-result-col').style.display='none';"
    +   "document.getElementById(id+'-ed-use').style.display='none';"
    +   "document.getElementById(id+'-ed-rmbg').textContent='Remove Background Again';"
    +   "lfBlobs[id]=null;"
    + "}"
    // For already-uploaded logos: fetch current image, process, preview
    + "async function lfRemoveBgExisting(id,imgPath){"
    +   "var btn=document.getElementById(id+'-existing-rmbg');"
    +   "btn.disabled=true;btn.textContent='Processing\u2026';"
    +   "try{"
    +     "var res=await fetch(imgPath);var sourceBlob=await res.blob();"
    +     "var blob=await lfRunRemoveBg(sourceBlob);"
    +     "lfBlobs[id+'_existing']=blob;"
    +     "document.getElementById(id+'-existing-result').src=URL.createObjectURL(blob);"
    +     "document.getElementById(id+'-existing-result-col').style.display='flex';"
    +     "document.getElementById(id+'-existing-use').style.display='';"
    +     "btn.textContent='Remove Background';btn.disabled=false;"
    +   "}catch(e){btn.textContent='Failed \u2013 Try Again';btn.disabled=false;console.error('rmbg-existing:',e);alert(e.message);}"
    + "}"
    + "async function lfUseExistingResult(id,logoType){"
    +   "var blob=lfBlobs[id+'_existing'];if(!blob)return;"
    +   "var btn=document.getElementById(id+'-existing-use').querySelector('button');"
    +   "btn.textContent='Saving\u2026';btn.disabled=true;"
    +   "try{"
    +     "var res=await fetch(window.location.pathname.replace('/brand','')+'/logo/'+logoType,{method:'POST',headers:{'Content-Type':'image/png'},body:blob});"
    +     "if(!res.ok)throw new Error('Upload failed');"
    +     "document.getElementById(id+'-current-img').src=window.location.pathname.replace('/brand','')+'/logo/'+logoType+'?t='+Date.now();"
    +     "document.getElementById(id+'-existing-result-col').style.display='none';"
    +     "document.getElementById(id+'-existing-use').style.display='none';"
    +     "document.getElementById(id+'-existing-rmbg').textContent='Remove Background Again';"
    +     "lfBlobs[id+'_existing']=null;"
    +   "}catch(e){btn.textContent='\u2713 Use This';btn.disabled=false;alert('Save failed: '+e.message);}"
    + "}"
    + "<\/script>"
    + navFabJS()
    + "</body></html>";
}
