import { buildSlots } from '../../constants.js';
import { editCSS } from '../css.js';
import { header, grid, footer, defaultJerseys } from '../components.js';

export function editPage(state, config, teamId, session, myTeams) {
  var s = state || {};
  var isSet = s.isSet || false;

  var js = "function refreshDisabled(){}"
    + "function setPlayer(slot,name){"
    + "var p=ROSTER.find(function(r){return r[1]===name;});"
    + "var el=document.getElementById(slot+\"-num\");"
    + "if(el)el.textContent=p&&p[0]?p[0]:\"\";"
    + "var sel=document.getElementById(slot+\"-sel\");if(sel)sel.setAttribute(\"data-value\",name);"
    + "var lbl=document.getElementById(slot+\"-lbl\");if(lbl)lbl.textContent=name;"
    + "}"
    + "function readableColor(hex){if(!hex||hex.length<7)return\"#1a1a1a\";var r=parseInt(hex.slice(1,3),16),g=parseInt(hex.slice(3,5),16),b=parseInt(hex.slice(5,7),16);return(0.299*r+0.587*g+0.114*b)>180?\"#1a1a1a\":hex;}"
    + "function updateJerseyColor(){"
    + "var sel=document.getElementById(\"jersey-color\");"
    + "var j=JERSEY_CONFIG.find(function(j){return j.id===sel.value;});"
    + "sel.style.color=readableColor(j?j.color:\"#1a1a1a\");"
    + "}"
    + "function getState(){"
    + "var state={opponent:document.getElementById(\"opponent\").value,gamedate:document.getElementById(\"gamedate\").value,gametime:document.getElementById(\"gametime\").value,rink:document.getElementById(\"rink\").value,jersey:document.getElementById(\"jersey-color\").value,homeaway:document.getElementById(\"home-away\").value,notes:document.getElementById(\"game-notes\").value};"
    + "SLOTS.forEach(function(slot){state[slot]=document.getElementById(slot+\"-sel\").getAttribute(\"data-value\")||\"\";"
    + "});"
    + "return state;}"
    + "function updateSetCount(){var filled=SLOTS.filter(function(s){var el=document.getElementById(s+'-sel');return el&&el.getAttribute('data-value');}).length;var total=SLOTS.length;var el=document.getElementById('set-count');if(!el)return;el.textContent=filled+' / '+total+' players filled';el.className='set-count'+(filled===total?' complete':'');}"
    + "var saveTimer=null;"
    + "function snapTime(el){var parts=el.value.split(\":\");if(parts.length<2)return;var h=parseInt(parts[0],10);var m=parseInt(parts[1],10);var snapped=Math.round(m/10)*10;if(snapped===60){snapped=0;h=(h+1)%24;}el.value=(h<10?\"0\"+h:h)+\":\"+( snapped<10?\"0\"+snapped:snapped);}"+ "function scheduleAutoSave(){setStatus(\"saving\");updateSetCount();clearTimeout(saveTimer);saveTimer=setTimeout(doSave,1000);}"
    + "function doSave(){var state=getState();fetch(BASE_URL+\"/save\",{method:\"POST\",headers:{\"Content-Type\":\"application/json\"},body:JSON.stringify(state)}).then(function(r){setStatus(r.ok?\"saved\":\"error\");}).catch(function(){setStatus(\"error\");});}"
    + "function setStatus(s){var el=document.getElementById(\"save-status\");if(s===\"saving\"){el.textContent=\"Saving...\";el.className=\"save-status saving\";}else if(s===\"saved\"){el.textContent=\"All changes saved\";el.className=\"save-status saved\";}else{el.textContent=\"Save failed\";el.className=\"save-status\";}}"
    + "function savePNG(){doSave();setTimeout(function(){window.location.href=BASE_URL+\"/view?export=png\";},600);}"
    + "function printLineup(){doSave();setTimeout(function(){window.location.href=BASE_URL+\"/view?export=print\";},600);}"
    + "function shareLineup(){var url=window.location.origin+BASE_URL+\"/view\";if(navigator.share){navigator.share({title:TEAM_NAME+\" Lineup\",url:url});}else if(navigator.clipboard){navigator.clipboard.writeText(url).then(function(){alert(\"Link copied!\\n\"+url);});}else{prompt(\"Copy this link:\",url);}}"
    + "function toggleSet(){clearTimeout(saveTimer);var state=getState();fetch(BASE_URL+\"/save\",{method:\"POST\",headers:{\"Content-Type\":\"application/json\"},body:JSON.stringify(state)}).then(function(){return fetch(BASE_URL+\"/toggle-status\",{method:\"POST\"});}).then(function(r){return r.json();}).then(function(data){setStatus(\"saved\");var item=document.getElementById(\"set-item\");var box=document.getElementById(\"set-check-box\");var lbl=document.getElementById(\"set-bar-label\");if(data.isSet){item.innerHTML=\"Lineup Set &#10003;\";item.classList.add(\"active\");box.innerHTML=\"&#10003;\";box.classList.add(\"checked\");lbl.textContent=\"Lineup Set\";}else{item.textContent=\"Mark as Set\";item.classList.remove(\"active\");box.innerHTML=\"\";box.classList.remove(\"checked\");lbl.textContent=\"Mark Lineup as Set\";}}).catch(function(){});}"
    + "function logout(){fetch(\"/logout\",{method:\"POST\"}).then(function(){window.location.href=\"/login\";});}"
    + "function clearAll(){if(!confirm(\"Clear all fields? This cannot be undone.\"))return;document.getElementById(\"opponent\").value=\"\";document.getElementById(\"gamedate\").value=\"\";document.getElementById(\"gametime\").value=\"\";document.getElementById(\"rink\").value=\"\";document.getElementById(\"game-notes\").value=\"\";SLOTS.forEach(function(slot){var sel=document.getElementById(slot+\"-sel\");if(sel)sel.setAttribute(\"data-value\",\"\");var lbl=document.getElementById(slot+\"-lbl\");if(lbl)lbl.textContent=\"\";var num=document.getElementById(slot+\"-num\");if(num)num.textContent=\"\";});document.getElementById(\"fab-menu\").classList.remove(\"open\");doSave();}"
    + "function syncRoster(){if(!confirm(\"Pull latest roster and opponents from ChillerStats? This will overwrite the current roster.\"))return;fetch(BASE_URL+\"/sync\",{method:\"POST\"}).then(function(r){if(r.ok){location.reload();}else{r.text().then(function(t){alert(\"Sync failed: \"+t);});}}).catch(function(){alert(\"Sync failed.\");});}"
    + "function fillNextGame(){document.getElementById(\"fab-menu\").classList.remove(\"open\");var _nb=document.getElementById('next-game-banner');if(_nb)_nb.remove();"
    + "fetch(BASE_URL+\"/next-game\").then(function(r){return r.json();}).then(function(game){"
    + "if(!game){alert(\"No upcoming game found.\");return;}"
    + "if(game.date)document.getElementById(\"gamedate\").value=game.date;"
    + "if(game.time)document.getElementById(\"gametime\").value=game.time;"
    + "if(game.rink){var rs=document.getElementById(\"rink\");rs.value=game.rink;sizeRinkSelect(rs);}"
    + "if(game.opponent){document.getElementById(\"opponent\").value=game.opponent;}"
    + "if(game.isHome!==null&&game.isHome!==undefined){document.getElementById(\"home-away\").value=game.isHome?\"home\":\"away\";}"
    + "scheduleAutoSave();}).catch(function(){alert(\"Could not fetch next game.\");});}"
    + "function toggleFab(){var m=document.getElementById(\"fab-menu\");m.classList.toggle(\"open\");document.body.style.overflow=m.classList.contains(\"open\")&&window.innerWidth<=599?\"hidden\":\"\";}"
    + "document.addEventListener(\"click\",function(e){if(!e.target.closest(\".fab\")){document.getElementById(\"fab-menu\").classList.remove(\"open\");document.body.style.overflow=\"\";}});"
    + "function sizeRinkSelect(sel){var txt=sel.options[sel.selectedIndex]?sel.options[sel.selectedIndex].text:'';var tmp=document.createElement('span');tmp.style.cssText='visibility:hidden;position:absolute;font-family:NHLChicago,Arial,sans-serif;font-size:'+getComputedStyle(sel).fontSize+';text-transform:uppercase;letter-spacing:1px;white-space:nowrap';tmp.textContent=txt;document.body.appendChild(tmp);sel.style.width=(tmp.offsetWidth+32)+'px';document.body.removeChild(tmp);}"
    + "(function(){var r=document.getElementById('rink');if(r)sizeRinkSelect(r);})();"
    + "if(!document.getElementById(\"gamedate\").value){document.getElementById(\"gamedate\").value=new Date().toISOString().split(\"T\")[0];}"
    + "updateSetCount();"
    + (config.chillerTeamId
      ? "var _availMap={};"
        + "function applyAvailPrefixes(){}"
        + "function fetchAvailability(){"
        + "fetch(BASE_URL+\"/availability\").then(function(r){return r.json();}).then(function(data){"
        + "if(!data||!data.availability||!data.availability.length)return;"
        + "data.availability.forEach(function(a){_availMap[a.name]=a.status;});"
        + "applyAvailPrefixes();"
        + "var yes=0,no=0,maybe=0;"
        + "data.availability.forEach(function(a){if(a.status===\"yes\")yes++;else if(a.status===\"no\")no++;else if(a.status===\"maybe\")maybe++;});"
        + "var rosterSize=MANAGED_ROSTER?MANAGED_ROSTER.filter(function(p){return p.name&&!p.isSub;}).length:0;"
        + "var responded=yes+no+maybe;"
        + "var noResp=rosterSize>responded?rosterSize-responded:0;"
        + "var bar=document.getElementById(\"avail-bar\");"
        + "if(bar){var chip=function(bg,col,txt){return\"<span style='background:\"+bg+\";color:\"+col+\";border-radius:20px;padding:3px 11px;font-size:11px;font-weight:600;letter-spacing:.3px'>\"+txt+\"</span>\";};"
        + "bar.innerHTML=chip(\"#e8f5e9\",\"#2e7d32\",\"\u2713 \"+yes+\" In\")+chip(\"#fff8e1\",\"#e65100\",\"? \"+maybe+\" Maybe\")+chip(\"#fce4ec\",\"#c62828\",\"\u2717 \"+no+\" Out\")+chip(\"#f0f0f0\",\"#888\",\"- \"+noResp+\" No Response\");"
        + "bar.style.display=\"flex\";}"
        + "}).catch(function(){});}"
        + "setTimeout(fetchAvailability,200);"
      : "");

  return "<!DOCTYPE html><html lang=\"en\"><head>"
    + "<meta charset=\"UTF-8\"><meta name=\"viewport\" content=\"width=device-width,initial-scale=1.0\">"
    + "<title>" + config.name + " \u2014 Lineup</title>"
    + "<style>" + editCSS(config) + "</style>"
    + "</head><body style=\"padding-bottom:72px\">"
    + "<div class=\"top-bar\"><span class=\"save-status\" id=\"save-status\"></span>"
    + "<div class=\"fab\"><button class=\"fab-btn\" onclick=\"toggleFab()\">&#9776;</button>"
    + "<div class=\"fab-menu\" id=\"fab-menu\">"
    + "<div class=\"fab-close\"><span class=\"fab-close-title\">Menu</span><button class=\"fab-close-btn\" onclick=\"toggleFab()\">&#215;</button></div>"
    + (myTeams && myTeams.length > 1 ? "<div class=\"fab-section-label\">My Teams</div>" + myTeams.map(function(t) { return "<a class=\"fab-item" + (t.slug === teamId ? " active" : "") + "\" href=\"/" + t.slug + "/\">" + t.name + "<span class=\"fab-item-tip\"><span class=\"fab-tip-icon\">&#9432;</span><span class=\"fab-tip-text\">Switch to the " + t.name + " lineup card</span></span></a>"; }).join("") + "<div class=\"fab-divider\"></div>" : "")
    + "<div class=\"fab-section-label\">Game</div>"
    + (config.chillerTeamId ? "<button class=\"fab-item\" onclick=\"fillNextGame()\">Fill Next Game<span class=\"fab-item-tip\"><span class=\"fab-tip-icon\">&#9432;</span><span class=\"fab-tip-text\">Auto-fill game details from your ChillerStats schedule</span></span></button>" : "")
    + "<button class=\"fab-item" + (isSet ? " active" : "") + "\" id=\"set-item\" onclick=\"toggleSet()\">" + (isSet ? "Lineup Set &#10003;" : "Mark as Set") + "<span class=\"fab-item-tip\"><span class=\"fab-tip-icon\">&#9432;</span><span class=\"fab-tip-text\">Mark this lineup as final and save a snapshot to Lineup History</span></span></button>"
    + "<div class=\"fab-divider\"></div>"
    + "<div class=\"fab-section-label\">Share &amp; Export</div>"
    + "<button class=\"fab-item\" onclick=\"printLineup()\">Print<span class=\"fab-item-tip\"><span class=\"fab-tip-icon\">&#9432;</span><span class=\"fab-tip-text\">Print or save your lineup as a PDF</span></span></button>"
    + "<button class=\"fab-item\" onclick=\"savePNG()\">Save as PNG<span class=\"fab-item-tip\"><span class=\"fab-tip-icon\">&#9432;</span><span class=\"fab-tip-text\">Download your lineup as an image file</span></span></button>"
    + "<button class=\"fab-item\" onclick=\"shareLineup()\">Share Link<span class=\"fab-item-tip\"><span class=\"fab-tip-icon\">&#9432;</span><span class=\"fab-tip-text\">Copy a shareable link to view this lineup</span></span></button>"
    + "<div class=\"fab-divider\"></div>"
    + "<div class=\"fab-section-label\">Roster &amp; History</div>"
    + "<a class=\"fab-item\" href=\"/" + teamId + "/history\">Lineup History<span class=\"fab-item-tip\"><span class=\"fab-tip-icon\">&#9432;</span><span class=\"fab-tip-text\">View past lineups you've marked as Set</span></span></a>"
    + "<a class=\"fab-item\" href=\"/" + teamId + "/roster\">Manage Roster<span class=\"fab-item-tip\"><span class=\"fab-tip-icon\">&#9432;</span><span class=\"fab-tip-text\">Add, remove, or update your team's players</span></span></a>"
    + (config.chillerTeamId ? "<a class=\"fab-item\" href=\"/" + teamId + "/schedule\">Season Schedule<span class=\"fab-item-tip\"><span class=\"fab-tip-icon\">&#9432;</span><span class=\"fab-tip-text\">View full season schedule, results, and record</span></span></a>" : "")
    + (config.chillerTeamId ? "<button class=\"fab-item\" onclick=\"syncRoster()\">Sync Roster<span class=\"fab-item-tip\"><span class=\"fab-tip-icon\">&#9432;</span><span class=\"fab-tip-text\">Pull the latest roster and schedule from ChillerStats</span></span></button>" : "")
    + "<div class=\"fab-divider\"></div>"
    + "<div class=\"fab-section-label\">Account</div>"
    + "<a class=\"fab-item\" href=\"/" + teamId + "/brand\">Team Settings<span class=\"fab-item-tip\"><span class=\"fab-tip-icon\">&#9432;</span><span class=\"fab-tip-text\">Update team colors, logo, and lineup options</span></span></a>"
    + "<a class=\"fab-item\" href=\"/signup\">Add a Team<span class=\"fab-item-tip\"><span class=\"fab-tip-icon\">&#9432;</span><span class=\"fab-tip-text\">Create a new team on Linemate</span></span></a>"
    + (session && session.role === "superadmin" ? "<a class=\"fab-item\" href=\"/admin\">Admin</a>" : "")
    + "<div class=\"fab-divider\"></div>"
    + "<button class=\"fab-item danger\" onclick=\"logout()\">Log Out<span class=\"fab-item-tip\"><span class=\"fab-tip-icon\">&#9432;</span><span class=\"fab-tip-text\">Sign out of your account</span></span></button>"
    + "</div></div></div>"
    + "<div class=\"card\">" + header(s,"edit",config)
    + (config.nextGame ? (function(){
        var ng = config.nextGame;
        var haDate = ng.isHome === true ? " \u00b7 Home" : ng.isHome === false ? " \u00b7 Away" : "";
        var dateStr = ng.date ? (function(d){var p=d.split("-");return p[1]+"/"+p[2];}).call(null,ng.date) : "";
        var timeStr = ng.time ? (function(t){var p=t.split(":");var h=parseInt(p[0]);var m=p[1];var ap=h>=12?"PM":"AM";h=h%12||12;return h+":"+m+" "+ap;}).call(null,ng.time) : "";
        var parts = ["vs. <strong>" + ng.opponent + "</strong>"];
        if (dateStr) parts.push(dateStr);
        if (timeStr) parts.push(timeStr);
        if (ng.rink) parts.push("@ " + ng.rink);
        if (haDate) parts.push(haDate.trim().replace(" \u00b7 ",""));
        return "<div class=\"next-game-banner\" id=\"next-game-banner\"><span class=\"next-game-text\">Next: " + parts.join(" &middot; ") + "</span><button class=\"next-game-load\" onclick=\"fillNextGame()\">Load &rarr;</button></div>";
      })() : "")
    + (config.chillerTeamId ? "<div id=\"avail-bar\" style=\"display:none;flex-wrap:wrap;justify-content:center;gap:6px;padding:8px 0 4px;\"></div>" : "")
    + grid(s,"edit",config)
    + "<div class=\"game-notes-wrap\">"
    + "<div class=\"game-notes-label\">Game Notes"
    + "<div class=\"info-wrap\"><span class=\"info-icon\">&#9432;</span><div class=\"info-tip\">Optional notes visible on the printed/shared lineup. Leave blank to hide. Use for lineup changes, powerplay lines, etc.</div></div>"
    + "</div>"
    + "<textarea class=\"game-notes-input\" id=\"game-notes\" placeholder=\"e.g. PP1: Smith, Jones, Williams, Brown, Davis\" oninput=\"scheduleAutoSave()\">" + (s.notes ? s.notes.replace(/</g,"&lt;").replace(/>/g,"&gt;") : "") + "</textarea>"
    + "</div>"
    + footer(config, true) + "</div>"
    + "<div class=\"set-bar\"><div class=\"set-bar-inner\">"
    + "<div class=\"set-check\" onclick=\"toggleSet()\">"
    + "<div class=\"check-box" + (isSet ? " checked" : "") + "\" id=\"set-check-box\">" + (isSet ? "&#10003;" : "") + "</div>"
    + "<div style=\"display:flex;flex-direction:column;gap:1px\">"
    + "<span class=\"set-label\" id=\"set-bar-label\">" + (isSet ? "Lineup Set" : "Mark Lineup as Set") + "</span>"
    + "<span class=\"set-count\" id=\"set-count\"></span>"
    + "</div>"
    + "<div class=\"info-wrap\"><span class=\"info-icon\">&#9432;</span><div class=\"info-tip\">Marks this lineup as final and saves a snapshot to Lineup History.</div></div>"
    + "</div>"
    + "<div class=\"set-actions\">"
    + "<button class=\"clear-bar-btn\" onclick=\"clearAll()\">Clear All</button>"
    + "<div class=\"info-wrap\"><span class=\"info-icon\">&#9432;</span><div class=\"info-tip\">Clears all player selections and game details.</div></div>"
    + "</div>"
    + "</div></div>"
    + "<script>var BASE_URL=\"/" + teamId + "\";"
    + "var TEAM_NAME=" + JSON.stringify(config.name) + ";"
    + "var TEAM_SLUG=" + JSON.stringify(teamId) + ";"
    + "var ROSTER=" + JSON.stringify(config.roster) + ";"
    + "var DEFAULTS=" + JSON.stringify(config.defaults) + ";"
    + "var SLOTS=" + JSON.stringify(buildSlots(config.fwdLines || 3, config.defLines || (config.threeDefLines ? 3 : 2))) + ";"
    + "var JERSEY_CONFIG=" + JSON.stringify(config.jerseys || defaultJerseys()) + ";"
    + "var NEXT_GAME=" + JSON.stringify(config.nextGame || null) + ";"
    + "var MANAGED_ROSTER=" + JSON.stringify(config.managedRoster || null) + ";"
    + "var PLAYER_STATS=" + JSON.stringify(config.playerStats || []) + ";"
    + "var _hotMap=(function(){var m={};PLAYER_STATS.forEach(function(s){if(s.gp>0&&s.pts/s.gp>=1)m[s.name]=true;});return m;})();"
    + js
    + "var _pickerSlot=null;"
    + "function openPicker(slot){"
    + "_pickerSlot=slot;"
    + "var cur=document.getElementById(slot+'-sel').getAttribute('data-value')||'';"
    + "var used={};SLOTS.forEach(function(s){var v=document.getElementById(s+'-sel').getAttribute('data-value');if(v&&s!==slot)used[v]=true;});"
    + "var list=document.getElementById('pp-list');list.innerHTML='';"
    + "function addOpt(name,isSep){"
    + "if(isSep){var d=document.createElement('div');d.className='pp-sep';d.textContent=name;list.appendChild(d);return;}"
    + "var d=document.createElement('div');"
    + "var isUsed=!!used[name];"
    + "d.className='pp-opt'+(name===cur?' pp-sel':'')+(isUsed?' pp-used':'');"
    + "var avail=typeof _availMap!=='undefined'?_availMap[name]:'';"
    + "var pfx=avail==='yes'?'\u2713 ':avail==='no'?'\u2717 ':avail==='maybe'?'? ':'';"
    + "var fire=_hotMap[name]?'\uD83D\uDD25 ':'';"
    + "d.textContent=pfx+fire+name;"
    + "if(!isUsed)d.onclick=function(){pickPlayer(slot,name);};"
    + "list.appendChild(d);}"
    + "var bl=document.createElement('div');bl.className='pp-opt'+(cur===''?' pp-sel':'');bl.textContent='\u2014 Clear \u2014';bl.onclick=function(){pickPlayer(slot,'');};list.appendChild(bl);"
    + "if(MANAGED_ROSTER&&MANAGED_ROSTER.length>1){"
    + "MANAGED_ROSTER.filter(function(p){return p.name&&!p.isSub;}).forEach(function(p){addOpt(p.name);});"
    + "var subs=MANAGED_ROSTER.filter(function(p){return p.name&&p.isSub;});"
    + "if(subs.length){addOpt('\u2500\u2500 Subs \u2500\u2500',true);subs.forEach(function(p){addOpt(p.name);});}"
    + "}else{ROSTER.slice(1).forEach(function(r){if(r[1])addOpt(r[1]);});}"
    + "var overlay=document.getElementById('pp-overlay');overlay.classList.add('open');"
    + "if(window.innerWidth>=600){"
    + "var btn=document.querySelector('#'+slot+'-sel .cs-btn');"
    + "var rect=btn.getBoundingClientRect();"
    + "var panel=document.getElementById('pp-panel');"
    + "var row=btn.closest('.player-row');"
    + "var rowRect=row?row.getBoundingClientRect():rect;"
    + "panel.style.top=(rect.bottom+4)+'px';panel.style.left=rowRect.left+'px';panel.style.width=rowRect.width+'px';"
    + "document.body.style.overflow='';"
    + "}else{document.body.style.overflow='hidden';}}"
    + "function closePicker(){"
    + "document.getElementById('pp-overlay').classList.remove('open');"
    + "document.body.style.overflow='';_pickerSlot=null;}"
    + "function pickPlayer(slot,name){closePicker();setPlayer(slot,name);scheduleAutoSave();}"
    + "refreshDisabled();"
    + "<\/script>"
    + "<div id=\"pp-overlay\" onclick=\"if(event.target===this)closePicker()\">"
    + "<div id=\"pp-panel\">"
    + "<div id=\"pp-header\"><span>Select Player</span><button class=\"pp-close\" onclick=\"closePicker()\">&#215;</button></div>"
    + "<div id=\"pp-list\"></div>"
    + "</div></div>"
    + "</body></html>";
}
